### ISSUE TITLE
Doesn't take CPU affinity into account

### ISSUE THREAD

**Issue by jonhoo** [seanmonstar/num_cpus#12]
While `num_cpus()` gives the correct number of physical CPUs, it does not take into account which of those CPU's the current process is actually allowed to use. It would be neat to be able to specify which of the two numbers to get.

For example, consider a simple `num_cpus` program that just prints the value of `num_cpus::get();`, and then exits:

```
$ nproc
80
$ num_cpus
80
$ taskset -c 0,1 nproc
2
$ taskset -c 0,1 num_cpus
80
```

If it's at all helpful, the source for `nproc` (which is included in coreutils) can be seen [here](https://fossies.org/dox/coreutils-8.23/lib_2nproc_8c_source.html).

**Comment by seanmonstar** [comment]
I'd welcome a PR!

**Comment by jonhoo** [comment]
Seems like unless we want to do some deep systems level hackery, we'll have to wait for https://github.com/rust-lang/rfcs/issues/819
