### ISSUE TITLE
Number of CPUs detected incorrectly on systems using cgroups v2

### ISSUE THREAD

**Issue by OrionNebula** [seanmonstar/num_cpus#124]
Currently, cgroup properties `cpu.cfs_quota_us` and  `cpu.cfs_period_us` are used to determine the number of CPUs. These properties were removed in cgroups v2 and replaced with `cpu.max`. The standard library function `std::thread::available_parallelism` handles this correctly, detecting the cgroups version at runtime and using a separate routine for each: https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/thread.rs#L412

This is especially a problem for Rust daemons that use a tokio multi-threaded runtime (tokio can't use `available_parallelism` due to MSRV). Some distributions use cgroups v2 by default (Arch definitely does, and I've seen evidence that Debian >= 11 does as well), and CPU limits set in systemd are implemented with cgroups. This can lead to way more worker threads than would be reasonable on machines with a lot of cores.

For anyone looking for a workaround, you can instantiate the runtime yourself and use `available_parallelism` to set the number of worker threads: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b5083320c328bd5acb16216f0a0faf54

**Comment by seanmonstar** [comment]
Thanks for the report. Seems worth fixing. Would you like to submit a PR?

**Comment by OrionNebula** [comment]
PR submitted :) I've confirmed that it fixes things on my Arch machine.
