### ISSUE TITLE
Request: make a new release with updated `hermit-abi` dep

### ISSUE THREAD

**Issue by poliorcetics** [seanmonstar/num_cpus#131]
Are there tasks to do (issues, PR) before making a new release ? If so, how can I help ?

**Comment by pm100** [comment]
yes - that fact that you updated your dependency but didnt update you version and publish has not fixed clippy moaning about multiple revisions of hermit-abi

**Comment by LingMan** [comment]
The new version is out: https://github.com/seanmonstar/num_cpus/pull/128#issuecomment-1613143574
