### ISSUE TITLE
num_cpus::get() == 18446744073709551615

### ISSUE THREAD

**Issue by lambdaburrito** [seanmonstar/num_cpus#2]
`num_cpus::get()` is totally broken (or my Macbook Air has surpassed the axioms of physics and now has 18,446,744,073,709,551,615 cores). 

This is braking a lot of APIs so please treat this as urgent! 

I spotted it as I am using nickel.rs and my server wouldn't start and debugged it to find out that Hyper was throwing an arithmetic overflow at `server/mod.rs:90` and it's due to a broken `num_cpus::get()`

**Comment by zr40** [comment]
`18446744073709551615` is a 64 bit unsigned integer with all bits set. I suspect it's a `-1` signed integer being interpreted as unsigned.

**Comment by lambdaburrito** [comment]
Ok, I fixed it. It is due to wrong value to `libc::sysconf` as 84 is incorrect for Mac OS X; it should be 58. I will see if this is for Linux too; but I'm guessing so to be POSIX compliant.

**Comment by lambdaburrito** [comment]
Also, to fix this in the correct way, we should add a libc::_SC_NPROCESSORS_ONLN rather than hardcoding it.

**Comment by seanmonstar** [comment]
Sorry about the breakage. I do not have a Mac, and so tried asking for help
of people trying the PR. I got one to try it and said it worked, so I
published.

libc does not yet have that const. Hence it's hard-coded and has the const
in a comment.

**Comment by lambdaburrito** [comment]
My pull request to fix is left hardcoded until `libc` adds it as a constant. When it's added as a constant, you won't need any specific targeted  `get_num_cpus()` function. Once it's upstream, I will submit another pull request.

**Comment by seanmonstar** [comment]
Merged #4
