### ISSUE TITLE
Consider bumping the version to 1.0

### ISSUE THREAD

**Issue by ruuda** [seanmonstar/num_cpus#23]
A while ago the issue of crate stability on crates.io came up on Reddit. Steve Klabnik [suggested](https://www.reddit.com/r/rust/comments/4i0str/cargo_predictable_dependency_management/d2vcmmk) to nudge authors to release 1.0. Now the issue came up again [in this thread](https://internals.rust-lang.org/t/proposal-the-rust-platform/3745/39), so I’ll make the suggestion:

`num_cpus` has been on crates.io for more than a year. It’s been downloaded half a million times. It exposes a single function, whose signature or behaviour will likely never change. If there is any crate on crates.io that would be in the “obviously no bugs” rather than the “no obvious bugs” category, `num_cpus` would be a good candidate with its ~100 line implementation. The past five releases would not have been breaking changes if `num_cpus` were stable.

So, why not release 1.0?

**Comment by seanmonstar** [comment]
Good call. 1.0.0 is now published here and on crates.io.
