### ISSUE TITLE
Enchance tests

### ISSUE THREAD

**Issue by lambdaburrito** [seanmonstar/num_cpus#3]
I've checked that you only have one test case, to test it's a positive integer so I am not surprised that it didn't catch the broken `get()`. 

We need to add a test to make sure it's not a unrealistic number of cores.  The highest number of cores to date is 32,000 cores (TH2 until Cray's new server comes out).  I would recommend to set the upper bound as 236,450 => ceiling(e^2 * 32000)

**Comment by seanmonstar** [comment]
Merged with #4
