### ISSUE TITLE
_SC_NPROCESSORS_ONLN may not be reliable on Android

### ISSUE THREAD

**Issue by Ms2ger** [seanmonstar/num_cpus#34]
Quoting from `mozilla.dev.platform`:

> sysconf(_SC_NPROCESSORS_ONLN) is used a number of places in the tree to get
> a core count for parallel algorithms.  The web says that that phrase does
> not really return the number of available cores on ARM Linuxish systems in
> general, including Android - because the return value does not account for
> cores that are sleeping for power saving reasons.  (I've confirmed this
> locally on an ARM board.)  So you may get lucky when you ask.  Or not.
> 
> sysconf(_SC_NPROCESSORS_CONF) works better here.
> 
> JS engine issue with some background and links to other discussions:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1333059.

**Comment by seanmonstar** [comment]
Sounds like a reasonable change to me, then.

**Comment by seanmonstar** [comment]
#45 had to be reverted, `_SC_NPROCESSORS_CONF` is not defined in libc on Android.

**Comment by GuildMasterInfinite** [comment]
Sorry my pull request did not work, I submitted a [pull request](https://github.com/rust-lang/libc/pull/627) to `libc` now to add the `_SC_NPROCESSORS_CONF` constant. 

Once the pull request gets accepted, perhaps this issue could finally be closed.
