### ISSUE TITLE
_SC_NPROCESSORS_CONF doesn't exist on Android

### ISSUE THREAD

**Issue by CryZe** [seanmonstar/num_cpus#46]
num_cpus 1.6.1 broke semver on Android as _SC_NPROCESSORS_CONF doesn't exist on those platforms.

You can see it missing here: https://github.com/rust-lang/libc/blob/master/src/unix/notbsd/android/mod.rs#L257

So #45 needs to be partially reverted and 1.6.1 possibly yanked.

**Comment by kubo39** [comment]
It does not exist on the libc crate side.

**Comment by seanmonstar** [comment]
I was worried about this. So many `cfg(target_os ...)`, but don't currently have a way to test all the OSes. Funny though, that this was meant to actually fix Android, not break it.

**Comment by seanmonstar** [comment]
Reverted, 1.6.2 published, 1.6.1 yanked.
