### ISSUE TITLE
Possible to get hyper threading?

### ISSUE THREAD

**Issue by faern** [seanmonstar/num_cpus#5]
It would be very nice if it was possible to ask this library if HT is present or not.
Often when doing computationally intensive work in thread pools and similar using the full number of threads is not desired (at least not in my experience).
Having an X-core cpu with HT will make this library return 2X. Not very strange, this is how it usually works. The downside is that doing heavy computation on 2X threads gives very little performance boost compared to X threads and has the downside that it slows down the computer very much, specially if the same computer run anything with a GUI.

Would this be possible to query from the OS? Maybe I can have a look at this myself, but I don't have time now so I leave this here.

**Comment by seanmonstar** [comment]
Some Googling suggests that it's not super easy to do. I'd accept a pull request, though.

**Comment by pedrocr** [comment]
On linux this is possible by parsing /proc/cpuinfo, would that be acceptable?

**Comment by seanmonstar** [comment]
Probably. I've never looked into it myself.

**Comment by pedrocr** [comment]
To clarify, I'm sure it's possible and was just wondering if you'd consider that acceptable for the crate or if it's too much of a hack. The way to do it is basically:

```sh
cat /proc/cpuinfo | grep "core id" | sort -u | wc -l
```

**Comment by seanmonstar** [comment]
I imagine there are corresponding parameters to pass to a syscall to get
this information. I wouldn't want to be spawning a shell child process in
this crate.

**Comment by pedrocr** [comment]
Haven't found any way to do it with a syscall yet. But I wouldn't do it in shell. Just open /proc/cpuinfo in rust and parse the text.

**Comment by seanmonstar** [comment]
Oh of course. It does seem like there isn't a syscall. hwloc just parses
/proc/cpuinfo as well.

Seems fine then.

**Comment by pedrocr** [comment]
See PR #24 for an implementation that works on Linux

**Comment by seanmonstar** [comment]
v1.1.0 has ben published which includes `get_physical`. Compiles on all platforms, if it fails at any point (it definitely will on Windows) it resorts to `get()`. Patches to make it work on platforms where it fails are welcome.

**Comment by pmarcelll** [comment]
I have access to a server with two processors and the number of physical cores reported is incorrect:
```cores: logical: 56, physical: 14```
The ```physical id``` isn't taken into account for the two different CPUs.
I'll send a PR soon.

**Comment by bluss** [comment]
@pmarcelll Maybe you can praise or bash the approach(es) in #30

**Comment by seanmonstar** [comment]
I'm going to close this, as we already have it for unix, and I've opened #39 for tracking Windows support of this.
