### ISSUE TITLE
Test/document cgroups behavior

### ISSUE THREAD

**Issue by olix0r** [seanmonstar/num_cpus#80]
Linux [`cgroups(7)`](http://man7.org/linux/man-pages/man7/cgroups.7.html) can limit cpu shares for a process (typically via Docker). Processes that use `num_cpus`, however, may be shown the number of CPUs available on the host OS and not the CPU shares as provided by cgroups.

I'm not 100% sure of the state of things, but we should build a small dockerized demo application to validate that CPU limits are reflected through `num_cpus`. If it's not cgroups-aware, we should make it so.

**Comment by lucab** [comment]
Relevant related logic from OpenJDK 15: https://github.com/openjdk/jdk/blob/jdk-15%2B0/src/hotspot/os/linux/os_linux.cpp#L5391-L5403
